# Generated by Django 3.1.6 on 2021-03-24 16:01

from django.db import migrations, models
import django.db.models.deletion
import webapp.Validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('summary', models.CharField(max_length=100, validators=[webapp.Validator.TaskCreateForm(['@', '$', '!', '#', '%', '^', '*', '~'])])),
                ('description', models.CharField(max_length=200, validators=[webapp.Validator.TaskCreateForm(['@', '$', '!', '#', '%', '^', '*', '~'])])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('tasks', models.ManyToManyField(blank=True, to='webapp.Task')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='types', to='webapp.Type'),
        ),
    ]
