# Generated by Django 3.1.6 on 2021-04-01 10:31

from django.db import migrations, models
import django.db.models.deletion
import webapp.Validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=200, verbose_name='Описание')),
                ('begin_date', models.DateField(verbose_name='date')),
                ('expiration_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Задача проекта',
                'verbose_name_plural': 'Задачи проекта',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=100, validators=[webapp.Validator.MinLengthValidator(5)])),
                ('description', models.CharField(max_length=200, validators=[webapp.Validator.TaskCreateForm(['@', '$', '!', '#', '%', '^', '*', '~'])])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.project', verbose_name='Проект')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.status', verbose_name='Статус')),
                ('types', models.ManyToManyField(blank=True, related_name='types', to='webapp.Type')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_of_tasks',
            field=models.ManyToManyField(blank=True, related_name='project_tasks', to='webapp.Projects_tasks'),
        ),
    ]
