# Generated by Django 3.1.6 on 2021-03-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210311_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, to='webapp.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='webapp.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.status', verbose_name='Статус'),
        ),
    ]
