# Generated by Django 3.1.6 on 2021-03-25 11:04

from django.db import migrations, models
import webapp.Validator


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, validators=[webapp.Validator.MinLengthValidator(5)]),
        ),
    ]
