# Generated by Django 3.1.6 on 2021-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210314_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='types', to='webapp.Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='types_old',
            field=models.ManyToManyField(blank=True, related_name='types_old', to='webapp.Type'),
        ),
    ]
