# Generated by Django 3.1.6 on 2021-04-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210414_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.group', verbose_name='Группы'),
        ),
    ]
