# Generated by Django 3.1.6 on 2021-04-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_project_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
