# Generated by Django 3.1.6 on 2021-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_task',
        ),
        migrations.AddField(
            model_name='project',
            name='project_task',
            field=models.ManyToManyField(related_name='projects', to='webapp.Task', verbose_name='Проект'),
        ),
    ]
