# Generated by Django 3.1.6 on 2021-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210325_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_task',
            field=models.ManyToManyField(related_name='projects', to='webapp.Task', verbose_name='Задачи'),
        ),
        migrations.CreateModel(
            name='Projects_tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('tasks_of_project', models.ManyToManyField(blank=True, to='webapp.Project')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
