# Generated by Django 3.1.6 on 2021-03-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210314_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='types_old',
        ),
    ]
