# Generated by Django 3.1.6 on 2021-03-18 12:16

from django.db import migrations, models
import webapp.Validator


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_task_types_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200, validators=[webapp.Validator.TaskCreateForm(['@', '$', '!', '#', '%', '^', '*', '~'])]),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, validators=[webapp.Validator.TaskCreateForm(['@', '$', '!', '#', '%', '^', '*', '~'])]),
        ),
    ]
