# Generated by Django 3.1.6 on 2021-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210329_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_tasks',
            name='tasks_of_project',
            field=models.ManyToManyField(blank=True, to='webapp.Project'),
        ),
    ]
