# Generated by Django 3.2 on 2021-04-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210415_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='groups',
        ),
    ]
