# Generated by Django 3.1.6 on 2021-03-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210329_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
